# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene', models.IntegerField(default=0)),
                ('image_file', models.ImageField(default='Null', upload_to='images')),
                ('reference', models.BooleanField(default=False)),
                ('hidden_reference', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Observer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('evaluation started', models.DateTimeField(blank=True)),
                ('evaluation ended', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date rated', models.DateTimeField(blank=True)),
                ('rating', models.IntegerField(default=0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.Image')),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.Observer')),
            ],
        ),
    ]
