# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_auto_20160111_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observer',
            old_name='evaluation started',
            new_name='startTime',
        ),
    ]
