# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0005_auto_20160111_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='score',
        ),
    ]
